# Generated by Django 5.0.6 on 2024-07-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='TrackerID',
            new_name='trackerID',
        ),
    ]
